Munch(

	{'vm_state': u'active',
 'disk_config': u'MANUAL',
 'addresses': Munch({u'eta-hgi-prod-network-main': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:ca:f1:df', u'version': 4, u'addr': u'192.168.226.209', u'OS-EXT-IPS:type': u'fixed'}, {u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:ca:f1:df', u'version': 4, u'addr': u'172.27.82.149', u'OS-EXT-IPS:type': u'floating'}]}),
 'server_groups': None,
 'terminated_at': None,
 'os-extended-volumes:volumes_attached': [Munch({u'id': u'48d07cd0-75d9-433e-955d-007914c6e232'})],
 'image': Munch({'id': u'e214e9a6-0594-4697-9280-799bccefa66b',
 'name': u'eta-hgi-image-hail-base-0.2.3'}),
 'ramdisk_id': None,
 'user_data': None,
 'OS-EXT-SRV-ATTR:user_data': None,
 'OS-EXT-STS:task_state': None,
 'OS-EXT-STS:vm_state': u'active',
 'OS-EXT-SRV-ATTR:instance_name': None,
 'OS-EXT-SRV-ATTR:root_device_name': None,
 'OS-SRV-USG:launched_at': u'2019-08-19T10:01:06.000000',
 'flavor': Munch({u'id': u'2002',
 'name': u'm1.medium'}),
 'az': u'nova',
 'reservation_id': None,
 'id': u'b5867ca4-ad12-4cf1-b6c9-24dd554e0db9',
 'security_groups': [Munch({'description': u'Base set of secgroups',
 'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'security_group_rules': [Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'udp',
 'ethertype': 'IPv4',
 'port_range_max': 65535,
 'security_group_id': u'23f31ce9-70e7-432c-8008-cf6b8795c63c',
 'tenant_id': '',
 'port_range_min': 1,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'10.0.0.0/8', u'group': {},
 'project_id': '',
 'id': u'7d250ff9-8eb5-4a6a-b682-b341ce6c8a73'}), Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 65535,
 'security_group_id': u'23f31ce9-70e7-432c-8008-cf6b8795c63c',
 'tenant_id': '',
 'port_range_min': 1,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'10.0.0.0/8', u'group': {},
 'project_id': '',
 'id': u'80fb93fb-a4de-48b3-a1bc-223c9638de65'}), Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'icmp',
 'ethertype': 'IPv4',
 'port_range_max': None,
 'security_group_id': u'23f31ce9-70e7-432c-8008-cf6b8795c63c',
 'tenant_id': '',
 'port_range_min': None,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'0.0.0.0/0', u'group': {},
 'project_id': '',
 'id': u'c1a159d9-8ab2-4e2f-9738-d8c511c6c681'})],
 'id': u'23f31ce9-70e7-432c-8008-cf6b8795c63c',
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'project_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'properties': {},
 'name': u'eta-hgi-prod-secgroup-base'}), Munch({'description': u"Spark Master's Access",
 'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'security_group_rules': [Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 8888,
 'security_group_id': u'd3f40b77-9649-435a-b5ef-c84a911b8015',
 'tenant_id': '',
 'port_range_min': 8888,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'0.0.0.0/0', u'group': {},
 'project_id': '',
 'id': u'5457c133-70a6-4e4a-9702-665d955aa611'}), Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 65535,
 'security_group_id': u'd3f40b77-9649-435a-b5ef-c84a911b8015',
 'tenant_id': '',
 'port_range_min': 1,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {u'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1', u'name': u'eta-hgi-prod-secgroup-spark-slave'}},
 'remote_ip_prefix': None, u'group': {u'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1', u'name': u'eta-hgi-prod-secgroup-spark-slave'},
 'project_id': '',
 'id': u'5adae3f9-2c7b-451b-89bc-1ce9de1eb263'}), Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 7077,
 'security_group_id': u'd3f40b77-9649-435a-b5ef-c84a911b8015',
 'tenant_id': '',
 'port_range_min': 7077,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'0.0.0.0/0', u'group': {},
 'project_id': '',
 'id': u'93bd2eff-2e03-4913-b404-fd3bac9b7715'}), Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 80,
 'security_group_id': u'd3f40b77-9649-435a-b5ef-c84a911b8015',
 'tenant_id': '',
 'port_range_min': 80,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'0.0.0.0/0', u'group': {},
 'project_id': '',
 'id': u'd9f701e8-bc1c-43aa-ab46-c119a6f72ab9'}), Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 8080,
 'security_group_id': u'd3f40b77-9649-435a-b5ef-c84a911b8015',
 'tenant_id': '',
 'port_range_min': 8080,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'0.0.0.0/0', u'group': {},
 'project_id': '',
 'id': u'fb1faf09-964e-436c-be8b-09f0eadca506'})],
 'id': u'd3f40b77-9649-435a-b5ef-c84a911b8015',
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'project_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'properties': {},
 'name': u'eta-hgi-prod-secgroup-spark-master'}), Munch({'description': u'SSH Access',
 'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'security_group_rules': [Munch({'remote_group_id': None,
 'direction': 'ingress',
 'protocol': u'tcp',
 'ethertype': 'IPv4',
 'port_range_max': 22,
 'security_group_id': u'e8ecee51-e1fb-497a-bfe4-822972692335',
 'tenant_id': '',
 'port_range_min': 22,
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'properties': {u'group': {}},
 'remote_ip_prefix': u'0.0.0.0/0', u'group': {},
 'project_id': '',
 'id': u'fd3e6029-2300-43b0-954c-acf1cc626387'})],
 'id': u'e8ecee51-e1fb-497a-bfe4-822972692335',
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'zone': None,
 'region_name': 'regionOne',
 'cloud': 'envvars'}),
 'project_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'properties': {},
 'name': u'eta-hgi-prod-secgroup-ssh'})],
 'scheduler_hints': None,
 'instance_name': None,
 'user_id': u'ef39696b4f944488bd8959a3e26cf1d2',
 'OS-EXT-SRV-ATTR:hostname': None,
 'hostname': None,
 'OS-DCF:diskConfig': u'MANUAL',
 'OS-EXT-SRV-ATTR:reservation_id': None,
 'networks': {},
 'accessIPv4': u'172.27.82.149',
 'accessIPv6': '',
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': u'nova'}),
 'power_state': 1,
 'public_v4': u'172.27.82.149',
 'progress': 0,
 'OS-EXT-STS:power_state': 1,
 'interface_ip': u'172.27.82.149',
 'launched_at': u'2019-08-19T10:01:06.000000',
 'OS-SRV-USG:terminated_at': None,
 'metadata': Munch({u'datacenter': u'eta', u'deployment_color': u'blue', u'deployment_name': u'hail', u'role_name': u'hail-master', u'env': u'prod', u'role_version': u'tenant/hgi', u'programme': u'hgi', u'deployment_owner': u'pa10'}),
 'status': u'ACTIVE',
 'OS-EXT-SRV-ATTR:ramdisk_id': None,
 'updated': u'2019-08-19T10:01:07Z',
 'hostId': u'c8677ee820b7849d134a4ccfeab2186a16c31e8d198628f363638b17',
 'OS-EXT-SRV-ATTR:host': None,
 'description': None,
 'block_device_mapping': None,
 'kernel_id': None,
 'key_name': u'eta-hgi-keypair-pa10',
 'public_v6': '',
 'hypervisor_hostname': None,
 'private_v4': u'192.168.226.209',
 'host': None,
 'OS-EXT-SRV-ATTR:kernel_id': None,
 'OS-SCH-HNT:scheduler_hints': None,
 'host_id': u'c8677ee820b7849d134a4ccfeab2186a16c31e8d198628f363638b17',
 'task_state': None,
 'properties': Munch({'OS-EXT-STS:task_state': None,
 'OS-EXT-SRV-ATTR:user_data': None,
 'OS-EXT-STS:vm_state': u'active',
 'OS-EXT-SRV-ATTR:instance_name': None,
 'OS-EXT-SRV-ATTR:root_device_name': None,
 'OS-SRV-USG:launched_at': u'2019-08-19T10:01:06.000000',
 'os-extended-volumes:volumes_attached': [Munch({u'id': u'48d07cd0-75d9-433e-955d-007914c6e232'})],
 'OS-EXT-SRV-ATTR:hostname': None,
 'OS-DCF:diskConfig': u'MANUAL',
 'OS-SCH-HNT:scheduler_hints': None,
 'OS-EXT-STS:power_state': 1,
 'OS-EXT-AZ:availability_zone': u'nova',
 'OS-EXT-SRV-ATTR:ramdisk_id': None,
 'OS-EXT-SRV-ATTR:host': None,
 'OS-SRV-USG:terminated_at': None,
 'OS-EXT-SRV-ATTR:reservation_id': None,
 'OS-EXT-SRV-ATTR:kernel_id': None,
 'OS-EXT-SRV-ATTR:hypervisor_hostname': None,
 'locked': None,
 'OS-EXT-SRV-ATTR:launch_index': None,
 'host_status': None,
 'trusted_image_certificates': None}),
 'tags': [],
 'OS-EXT-AZ:availability_zone': u'nova',
 'host_status': None,
 'project_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'OS-EXT-SRV-ATTR:hypervisor_hostname': None,
 'name': u'eta-hgi-prod-instance-pa10-hail-hail-master-01',
 'OS-EXT-SRV-ATTR:launch_index': None,
 'adminPass': None,
 'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'created_at': u'2019-08-19T10:01:01Z',
 'created': u'2019-08-19T10:01:01Z',
 'launch_index': None,
 'locked': None,
 'has_config_drive': False,
 'trusted_image_certificates': None,
 'root_device_name': None,
 'volumes': [],
 'cloud': 'envvars',
 'personality': None,
 'config_drive': u'',
 'region': 'regionOne'})






[


Munch({'vm_state': u'active',
 'disk_config': u'MANUAL',
 'addresses': Munch({u'eta-hgi-prod-network-main': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:3e:f2:41', u'version': 4, u'addr': u'192.168.226.164', u'OS-EXT-IPS:type': u'fixed'}]}),
 'server_groups': None,
 'terminated_at': None,
 'os-extended-volumes:volumes_attached': [],
 'image': Munch({'id': u'e214e9a6-0594-4697-9280-799bccefa66b'}),
 'ramdisk_id': None,
 'user_data': None,
 'OS-EXT-SRV-ATTR:user_data': None,
 'OS-EXT-STS:task_state': None,
 'OS-EXT-STS:vm_state': u'active',
 'OS-EXT-SRV-ATTR:instance_name': None,
 'OS-EXT-SRV-ATTR:root_device_name': None,
 'OS-SRV-USG:launched_at': u'2019-08-19T10:06:01.000000',
 'flavor': Munch({u'id': u'2002'}),
 'az': u'nova',
 'reservation_id': None,
 'id': u'0d36edfb-581c-4500-9c81-ab7df8c2cce9',
 'security_groups': [Munch({u'name': u'eta-hgi-prod-secgroup-base'}), Munch({u'name': u'eta-hgi-prod-secgroup-spark-slave'}), Munch({u'name': u'eta-hgi-prod-secgroup-ssh'})],
 'scheduler_hints': None,
 'instance_name': None,
 'user_id': u'ef39696b4f944488bd8959a3e26cf1d2',
 'OS-EXT-SRV-ATTR:hostname': None,
 'hostname': None,
 'OS-DCF:diskConfig': u'MANUAL',
 'OS-EXT-SRV-ATTR:reservation_id': None,
 'networks': {},
 'accessIPv4': '',
 'accessIPv6': '',
 'location': Munch({'project': Munch({'domain_id': 'default',
 'id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_name': None}),
 'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': u'nova'}),
 'power_state': 1,
 'public_v4': '',
 'progress': 0,
 'OS-EXT-STS:power_state': 1,
 'interface_ip': '',
 'launched_at': u'2019-08-19T10:06:01.000000',
 'OS-SRV-USG:terminated_at': None,
 'metadata': Munch({u'datacenter': u'eta', u'deployment_color': u'blue', u'deployment_name': u'hail', u'role_name': u'hail-slave', u'env': u'prod', u'role_version': u'tenant/hgi', u'programme': u'hgi', u'deployment_owner': u'pa10'}),
 'status': u'ACTIVE',
 'OS-EXT-SRV-ATTR:ramdisk_id': None,
 'updated': u'2019-08-19T10:06:01Z',
 'hostId': u'97ac8460bb5e829c0a74b8488b2bdd7fbae6a37110a382685eb5c9e9',
 'OS-EXT-SRV-ATTR:host': None,
 'description': None,
 'block_device_mapping': None,
 'kernel_id': None,
 'key_name': u'eta-hgi-keypair-pa10',
 'public_v6': '',
 'hypervisor_hostname': None,
 'private_v4': u'192.168.226.164',
 'host': None,
 'OS-EXT-SRV-ATTR:kernel_id': None,
 'OS-SCH-HNT:scheduler_hints': None,
 'host_id': u'97ac8460bb5e829c0a74b8488b2bdd7fbae6a37110a382685eb5c9e9',
 'task_state': None,
 'properties': Munch({'OS-EXT-STS:task_state': None,
 'OS-EXT-SRV-ATTR:user_data': None,
 'OS-EXT-STS:vm_state': u'active',
 'OS-EXT-SRV-ATTR:instance_name': None,
 'OS-EXT-SRV-ATTR:root_device_name': None,
 'OS-SRV-USG:launched_at': u'2019-08-19T10:06:01.000000',
 'os-extended-volumes:volumes_attached': [],
 'OS-EXT-SRV-ATTR:hostname': None,
 'OS-DCF:diskConfig': u'MANUAL',
 'OS-SCH-HNT:scheduler_hints': None,
 'OS-EXT-STS:power_state': 1,
 'OS-EXT-AZ:availability_zone': u'nova',
 'OS-EXT-SRV-ATTR:ramdisk_id': None,
 'OS-EXT-SRV-ATTR:host': None,
 'OS-SRV-USG:terminated_at': None,
 'OS-EXT-SRV-ATTR:reservation_id': None,
 'OS-EXT-SRV-ATTR:kernel_id': None,
 'OS-EXT-SRV-ATTR:hypervisor_hostname': None,
 'locked': None,
 'OS-EXT-SRV-ATTR:launch_index': None,
 'host_status': None,
 'trusted_image_certificates': None}),
 'tags': [],
 'OS-EXT-AZ:availability_zone': u'nova',
 'host_status': None,
 'project_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'OS-EXT-SRV-ATTR:hypervisor_hostname': None,
 'name': u'eta-hgi-prod-instance-pa10-hail-hail-slave-77',
 'OS-EXT-SRV-ATTR:launch_index': None,
 'adminPass': None,
 'tenant_id': u'4a9207c32f884e188bc3fe8227ebb7a1',
 'created_at': u'2019-08-19T10:04:32Z',
 'created': u'2019-08-19T10:04:32Z',
 'launch_index': None,
 'locked': None,
 'has_config_drive': False,
 'trusted_image_certificates': None,
 'root_device_name': None,
 'volumes': [],
 'cloud': 'envvars',
 'personality': None,
 'config_drive': u'',
 'region': 'regionOne'}),


Flavours

Munch(
{'location': Munch({'cloud': 'envvars','region_name': 'regionOne',
 'zone': None,'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1','name': 'hgi','domain_id': 'default',
 'domain_name': None})}),
 'id': '2000',
 'name': 'm1.tiny',
 'is_public': True,
 'is_disabled': False,
 'ram': 8600,
 'vcpus': 1,
 'disk': 15,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'list_flavorOS-FLV-EXT-DATA:ephemeral': 0}), 


Munch({'location': Munch({'cloud': 'envvars','region_name': 'regionOne','zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default','domain_name': None})}),
 'id': '2001',
 'name': 'm1.small',
 'is_public': True,
 'is_disabled': False,
 'ram': 17200,
 'vcpus': 2,
 'disk': 31,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), 





Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2002',
 'name': 'm1.medium',
 'is_public': True,
 'is_disabled': False,
 'ram': 34400,
 'vcpus': 4,
 'disk': 62,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2003',
 'name': 'm1.large',
 'is_public': True,
 'is_disabled': False,
 'ram': 68800,
 'vcpus': 8,
 'disk': 125,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2004',
 'name': 'm1.xlarge',
 'is_public': True,
 'is_disabled': False,
 'ram': 137600,
 'vcpus': 16,
 'disk': 250,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2005',
 'name': 'm1.2xlarge',
 'is_public': True,
 'is_disabled': False,
 'ram': 223600,
 'vcpus': 26,
 'disk': 406,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2006',
 'name': 'm1.3xlarge',
 'is_public': True,
 'is_disabled': False,
 'ram': 464400,
 'vcpus': 54,
 'disk': 844,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m': 'true',
 'hw:cpu_policy': 'dedicated',
 'hw:numa_nodes': '2'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2100',
 'name': 'm2.tiny',
 'is_public': True,
 'is_disabled': False,
 'ram': 11190,
 'vcpus': 1,
 'disk': 28,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2101',
 'name': 'm2.small',
 'is_public': True,
 'is_disabled': False,
 'ram': 23800,
 'vcpus': 2,
 'disk': 56,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2102',
 'name': 'm2.medium',
 'is_public': True,
 'is_disabled': False,
 'ram': 47600,
 'vcpus': 4,
 'disk': 113,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2103',
 'name': 'm2.large',
 'is_public': True,
 'is_disabled': False,
 'ram': 95200,
 'vcpus': 8,
 'disk': 226,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2104',
 'name': 'm2.xlarge',
 'is_public': True,
 'is_disabled': False,
 'ram': 190400,
 'vcpus': 16,
 'disk': 453,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2105',
 'name': 'm2.2xlarge',
 'is_public': True,
 'is_disabled': False,
 'ram': 285600,
 'vcpus': 24,
 'disk': 680,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), Munch({'location': Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': None,
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}),
 'id': '2106',
 'name': 'm2.3xlarge',
 'is_public': True,
 'is_disabled': False,
 'ram': 357000,
 'vcpus': 30,
 'disk': 850,
 'ephemeral': 0,
 'swap': 0,
 'rxtx_factor': 1.0,
 'properties': Munch({'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}),
 'extra_specs': Munch({'aggregate_instance_extra_specs:m2': 'true'}),
 'OS-FLV-DISABLED:disabled': False,
 'os-flavor-access:is_public': True,
 'OS-FLV-EXT-DATA:ephemeral': 0}), 



server

Metadata openstack.compute.v2.server.Server(OS-EXT-STS:task_state=None, addresses={'eta-hgi-prod-network-main': [{'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:27:dd:10',
 'version': 4,
 'addr': '192.168.226.183',
 'OS-EXT-IPS:type': 'fixed'}]}, links=[{'href': 'https://eta.internal.sanger.ac.uk:13774/v2.1/servers/5bf8adc7-8c56-4db3-9b13-fee09d22c0a4',
 'rel': 'self'}, {'href': 'https://eta.internal.sanger.ac.uk:13774/servers/5bf8adc7-8c56-4db3-9b13-fee09d22c0a4',
 'rel': 'bookmark'}], image={'id': 'e214e9a6-0594-4697-9280-799bccefa66b',
 'links': [{'href': 'https://eta.internal.sanger.ac.uk:13774/images/e214e9a6-0594-4697-9280-799bccefa66b',
 'rel': 'bookmark'}]}, OS-EXT-STS:vm_state=active, OS-SRV-USG:launched_at=2019-08-20T10:41:06.000000, flavor={'id': '2002',
 'links': [{'href': 'https://eta.internal.sanger.ac.uk:13774/flavors/2002',
 'rel': 'bookmark'}]}, id=5bf8adc7-8c56-4db3-9b13-fee09d22c0a4, security_groups=[{'name': 'eta-hgi-prod-secgroup-base'}, {'name': 'eta-hgi-prod-secgroup-spark-slave'}, {'name': 'eta-hgi-prod-secgroup-ssh'}], user_id=ef39696b4f944488bd8959a3e26cf1d2, OS-DCF:diskConfig=MANUAL, accessIPv4=, accessIPv6=, progress=0, OS-EXT-STS:power_state=1, OS-EXT-AZ:availability_zone=nova, config_drive=, status=ACTIVE, updated=2019-08-20T10:41:06Z, hostId=b0b44f894e45a5364ec01dfe97d9f12cc325d0031a43597efbc597db, OS-SRV-USG:terminated_at=None, key_name=eta-hgi-keypair-pa10, name=eta-hgi-prod-instance-pa10-hail-hail-slave-83, created=2019-08-20T10:40:54Z, tenant_id=4a9207c32f884e188bc3fe8227ebb7a1, os-extended-volumes:volumes_attached=[], metadata={'datacenter': 'eta',
 'deployment_color': 'blue',
 'deployment_name': 'hail',
 'role_name': 'hail-slave',
 'env': 'prod',
 'role_version': 'tenant/hgi',
 'programme': 'hgi',
 'deployment_owner': 'pa10'}, location=Munch({'cloud': 'envvars',
 'region_name': 'regionOne',
 'zone': 'nova',
 'project': Munch({'id': '4a9207c32f884e188bc3fe8227ebb7a1',
 'name': 'hgi',
 'domain_id': 'default',
 'domain_name': None})}))


